apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "improved-rag-frontend.fullname" . }}
  labels:
    app: {{ include "improved-rag-frontend.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "improved-rag-frontend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "improved-rag-frontend.name" . }}
    spec:
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      containers:
        - name: improved-rag-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
