# .streamlit/config.toml

[theme]
primaryColor="#F63366"
backgroundColor="#00263A"  # Midnight Blue
secondaryBackgroundColor="#1F2324"  # Steel
textColor="#DBE2E9"  # Silver
font="sans serif"

[server]
maxUploadSize = 200
maxMessageSize = 200
port = 8501
address = "0.0.0.0"

[browser]
gatherUsageStats = false